In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

student_features_first_25 = pd.read_csv(r"C:\Users\Ahmed\Documents\GazaSkyGeeksOlmpics\project\tests\Fares\data\processed\student_features_first_25.csv"
)
student_features_first_25

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,disability,...,late_submissions_until_cutoff,avg_submission_delay_until_cutoff,avg_assessment_relative_time_until_cutoff,avg_submitted_relative_time_until_cutoff,avg_assessment_arab_day_until_cutoff,avg_submitted_arab_day_until_cutoff,avg_submission_delay_relative_until_cutoff,avg_submission_delay_arab_days_until_cutoff,workload_ratio,workload_level
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,N,...,0.0,-1.0,0.136194,0.132463,20.429104,19.869403,-0.003731,-0.559701,2.00,very_high
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,N,...,1.0,0.5,0.136194,0.138060,20.429104,20.708955,0.001866,0.279851,0.50,light
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,Y,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.50,light
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,N,...,0.0,-2.5,0.136194,0.126866,20.429104,19.029851,-0.009328,-1.399254,0.50,light
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,N,...,1.0,7.0,0.070896,0.097015,10.634328,14.552239,0.026119,3.917910,0.50,light
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32475,GGG,2014J,2640965,F,Wales,Lower Than A Level,10-20,0-35,0,N,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.25,light
32476,GGG,2014J,2645731,F,East Anglian Region,Lower Than A Level,40-50%,35-55,0,N,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.25,light
32477,GGG,2014J,2648187,F,South Region,A Level or Equivalent,20-30%,0-35,0,Y,...,0.0,-11.0,0.226766,0.185874,34.014870,27.881041,-0.040892,-6.133829,0.25,light
32478,GGG,2014J,2679821,F,South East Region,Lower Than A Level,90-100%,35-55,0,N,...,0.0,-5.0,0.226766,0.208178,34.014870,31.226766,-0.018587,-2.788104,0.25,light
32479,GGG,2014J,2684003,F,Yorkshire Region,HE Qualification,50-60%,35-55,0,N,...,0.0,-24.0,0.226766,0.137546,34.014870,20.631970,-0.089219,-13.382900,0.25,light

In [2]:
student_features_first_25.columns

Index(['code_module', 'code_presentation', 'id_student', 'gender', 'region',
       'highest_education', 'imd_band', 'age_band', 'num_of_prev_attempts',
       'disability', 'final_result', 'target', 'module_presentation_length',
       'active_days_until_cutoff', 'vle_module_presentation_length',
       'unique_sites_until_cutoff', 'unique_activity_types_until_cutoff',
       'clicks_per_active_day_until_cutoff', 'active_days_ratio_until_cutoff',
       'arab_active_days_equivalent_until_cutoff', 'dataplus', 'dualpane',
       'externalquiz', 'forumng', 'glossary', 'homepage', 'htmlactivity',
       'oucollaborate', 'oucontent', 'ouelluminate', 'ouwiki', 'page',
       'questionnaire', 'quiz', 'repeatactivity', 'resource', 'sharedsubpage',
       'subpage', 'url', 'avg_score_until_cutoff',
       'submitted_assessments_until_cutoff', 'late_submissions_until_cutoff',
       'avg_submission_delay_until_cutoff',
       'avg_assessment_relative_time_until_cutoff',
       'avg_submitted_relative_time_until_cutoff',
       'avg_assessment_arab_day_until_cutoff',
       'avg_submitted_arab_day_until_cutoff',
       'avg_submission_delay_relative_until_cutoff',
       'avg_submission_delay_arab_days_until_cutoff', 'workload_ratio',
       'workload_level'],
      dtype='object')

In [3]:
student_features_first_25 = student_features_first_25.copy()

print(student_features_first_25.shape)

student_features_first_25.head()

(32480, 51)

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,disability,...,late_submissions_until_cutoff,avg_submission_delay_until_cutoff,avg_assessment_relative_time_until_cutoff,avg_submitted_relative_time_until_cutoff,avg_assessment_arab_day_until_cutoff,avg_submitted_arab_day_until_cutoff,avg_submission_delay_relative_until_cutoff,avg_submission_delay_arab_days_until_cutoff,workload_ratio,workload_level
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,N,...,0.0,-1.0,0.136194,0.132463,20.429104,19.869403,-0.003731,-0.559701,2.0,very_high
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,N,...,1.0,0.5,0.136194,0.138060,20.429104,20.708955,0.001866,0.279851,0.5,light
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,Y,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.5,light
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,N,...,0.0,-2.5,0.136194,0.126866,20.429104,19.029851,-0.009328,-1.399254,0.5,light
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,N,...,1.0,7.0,0.070896,0.097015,10.634328,14.552239,0.026119,3.917910,0.5,light

In [4]:
numeric_df_25 = student_features_first_25.select_dtypes(include=["number"]).copy()

if "id_student" in numeric_df_25.columns:
    numeric_df_25 = numeric_df_25.drop(columns=["id_student"])

In [5]:
corr_matrix_25 = numeric_df_25.corr().abs()

In [6]:
import plotly.graph_objects as go

fig = go.Figure(
    data=go.Heatmap(
        z=corr_matrix_25.values,
        x=corr_matrix_25.columns,
        y=corr_matrix_25.columns,
        colorscale="RdBu",
        zmin=-1,
        zmax=1
    )
)

fig.update_layout(
    title="Correlation Heatmap - First 25%",
    width=1000,
    height=900
)

fig.show()

In [7]:
manual_drop_25 = [
    "max_score_until_cutoff",
    "min_score_until_cutoff",
    "studied_credits",
    "total_clicks_until_cutoff"
]

student_features_first_25 = student_features_first_25.drop(columns=manual_drop_25, errors="ignore")

print(student_features_first_25.shape)

(32480, 51)

In [8]:
from pathlib import Path

Path("data/processed").mkdir(
    parents=True,
    exist_ok=True
)   

student_features_first_25.to_csv(
    "data/processed/student_features_first_25.csv",
    index=False
)

print("student_features_first_25 saved successfully.")

student_features_first_25 saved successfully.

#### Now after saving the file of Q1, we'll choose (15) features with Arab-normalized time features and save it to
#### csv file named **Selected_features_Q1.csv**

In [ ]:
# Here we select the features that we will use in our model based on the correlation analysis and domain knowledge.
selected_features = [
    "avg_score_until_cutoff",
    "submitted_assessments_until_cutoff",
    "arab_active_days_equivalent_until_cutoff",
    "avg_submission_delay_arab_days_until_cutoff",
    "homepage",
    "age_band",
    "forumng",
    "unique_sites_until_cutoff",
    "unique_activity_types_until_cutoff",
    "clicks_per_active_day_until_cutoff",
    "resource",
    "subpage",
    "url",
    "oucontent",
    "quiz",
    "highest_education"
]


missing_features = [column for column in selected_features if column not in student_features_first_25.columns]
if missing_features:
    raise ValueError(f"Missing selected features: {missing_features}")

selected_df = student_features_first_25[selected_features + ["target"]]

selected_df.to_csv(
    "C:\\Users\\Ahmed\\Documents\\GazaSkyGeeksOlmpics\\project\\tests\\Fares\\data\\processed\\Selected_features_Q1.csv",
    index=False
)

print("Selected_features_Q1 saved successfully.")
print("Shape:", selected_df.shape)

Selected_features_Q1 saved successfully.
Shape: (32480, 36)